# Generated by Django 4.2.11 on 2024-09-13 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('Enroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolledcoursemodel',
            name='enrollcourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursemodel'),
        ),
        migrations.AddField(
            model_name='enrolledcoursemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
