# Generated by Django 4.2.11 on 2024-09-26 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0002_alter_reviewmodel_options_videomodel_course'),
        ('Enroll', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolledcoursemodel',
            name='enrollcourse',
        ),
        migrations.AddField(
            model_name='enrolledcoursemodel',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.coursemodel'),
        ),
        migrations.AddField(
            model_name='enrolledcoursemodel',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='enrolledcoursemodel',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='enrolledcoursemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
